name: Tag CI - Jason Ruesch

on:
  push:
    tags:
      - 'jasonruesch-v**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.ref }}
  cancel-in-progress: true

env:
  # Needed to remove the uknown/unknown OS/Arch from the docker container manifest
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

permissions: write-all

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    env:
      INPUT_PUSH: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm ci
      - uses: nrwl/nx-set-shas@v3

      - run: npx nx run jasonruesch:container
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      # Skip Nx cache to upload accurate build for deployment
      - run: npx nx build jasonruesch --skip-nx-cache

      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          # Upload dist repository
          path: './dist/jasonruesch'

      - uses: actions/deploy-pages@v2
        id: deployment
